Instance,Runtime (seconds),Feasible,Profit,Error
lrc53B.txt,0.69,No,-inf,"[Error running script: Command '['python3', 'main.py', '--instance_path', '/home/akkermanfr/competition_master/Instances/lrc53B.txt']' returned non-zero exit status 1.. Details: Traceback (most recent call last):
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-12/Group12/main.py"", line 74, in <module>
    sol = main(instance)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-12/Group12/main.py"", line 39, in main
    solution = local_search_swap(solution, instance_dict)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-12/Group12/local_search.py"", line 306, in local_search_swap
    swap2 = random.randrange(len(pairs2))
  File ""/usr/lib/python3.10/random.py"", line 321, in randrange
    raise ValueError(""empty range for randrange()"")
ValueError: empty range for randrange()
]"
lrc103B.txt,0.13,No,-inf,"[Error running script: Command '['python3', 'main.py', '--instance_path', '/home/akkermanfr/competition_master/Instances/lrc103B.txt']' returned non-zero exit status 1.. Details: Traceback (most recent call last):
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-12/Group12/main.py"", line 74, in <module>
    sol = main(instance)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-12/Group12/main.py"", line 39, in main
    solution = local_search_swap(solution, instance_dict)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-12/Group12/local_search.py"", line 318, in local_search_swap
    routes = move_within_route2(routes, route1, profit)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-12/Group12/local_search.py"", line 234, in move_within_route2
    if helper.total_profit_with_penalties(list_to_dict(routes), instances) > profit:
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-12/Group12/helper.py"", line 208, in total_profit_with_penalties
    x2, y2 = node_data[node_id_next]['x_coord'], node_data[node_id_next]['y_coord']
KeyError: 54
]"
lrc303B.txt,0.35,No,-inf,"[Error running script: Command '['python3', 'main.py', '--instance_path', '/home/akkermanfr/competition_master/Instances/lrc303B.txt']' returned non-zero exit status 1.. Details: Traceback (most recent call last):
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-12/Group12/main.py"", line 74, in <module>
    sol = main(instance)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-12/Group12/main.py"", line 39, in main
    solution = local_search_swap(solution, instance_dict)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-12/Group12/local_search.py"", line 318, in local_search_swap
    routes = move_within_route2(routes, route1, profit)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-12/Group12/local_search.py"", line 234, in move_within_route2
    if helper.total_profit_with_penalties(list_to_dict(routes), instances) > profit:
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-12/Group12/helper.py"", line 208, in total_profit_with_penalties
    x2, y2 = node_data[node_id_next]['x_coord'], node_data[node_id_next]['y_coord']
KeyError: 154
]"
