Instance,Runtime (seconds),Feasible,Profit,Error
lrc53B.txt,0.46,No,-inf,"[Error running script: Command '['python3', 'main.py', '--instance_path', '/home/akkermanfr/competition_master/Instances/lrc53B.txt']' returned non-zero exit status 1.. Details: Traceback (most recent call last):
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/main.py"", line 61, in <module>
    instance = read_instance(args.instance_path)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/helper.py"", line 10, in read_instance
    with open(filename, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '../data\\instances/lrc53A.txt'
]"
lrc103B.txt,0.46,No,-inf,"[Error running script: Command '['python3', 'main.py', '--instance_path', '/home/akkermanfr/competition_master/Instances/lrc103B.txt']' returned non-zero exit status 1.. Details: Traceback (most recent call last):
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/main.py"", line 61, in <module>
    instance = read_instance(args.instance_path)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/helper.py"", line 10, in read_instance
    with open(filename, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '../data\\instances/lrc53A.txt'
]"
lrc303B.txt,0.46,No,-inf,"[Error running script: Command '['python3', 'main.py', '--instance_path', '/home/akkermanfr/competition_master/Instances/lrc303B.txt']' returned non-zero exit status 1.. Details: Traceback (most recent call last):
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/main.py"", line 61, in <module>
    instance = read_instance(args.instance_path)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/helper.py"", line 10, in read_instance
    with open(filename, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: '../data\\instances/lrc53A.txt'
]"
