Instance,Runtime (seconds),Feasible,Profit,Error
lrc33.txt,0.51,No,-inf,"[Error running script: Command '['python3', 'main.py', '--instance_path', '/home/akkermanfr/competition_master/Instances/lrc33.txt']' returned non-zero exit status 1.. Details: Traceback (most recent call last):
  File ""/home/akkermanfr/repos/vrp-competition-submissions/vrp-competition-test2/Group2/main.py"", line 76, in <module>
    sol = main(instance)
  File ""/home/akkermanfr/repos/vrp-competition-submissions/vrp-competition-test2/Group2/main.py"", line 54, in main
    x = t[20]
IndexError: list index out of range
]"
lrc34.txt,0.51,No,-inf,"[Error running script: Command '['python3', 'main.py', '--instance_path', '/home/akkermanfr/competition_master/Instances/lrc34.txt']' returned non-zero exit status 1.. Details: Traceback (most recent call last):
  File ""/home/akkermanfr/repos/vrp-competition-submissions/vrp-competition-test2/Group2/main.py"", line 76, in <module>
    sol = main(instance)
  File ""/home/akkermanfr/repos/vrp-competition-submissions/vrp-competition-test2/Group2/main.py"", line 54, in main
    x = t[20]
IndexError: list index out of range
]"
